// website/app/layout.tsx — same no-FOUC `.dark`-class theme
// script as src/app/layout.tsx (not next-themes) so the site's dark/light
// behavior matches the app exactly. RootProvider mounts next-themes on the
// SAME storage key so the docs sidebar toggle really switches the class the
// script above pre-applies, and its search dialog reads the static index
// exported by app/api/search/route.ts.
import type { Metadata } from "next";
import { Fraunces, Inter, IBM_Plex_Mono } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider/next";
import "./global.css";

const fraunces = Fraunces({ variable: "--font-fraunces", subsets: ["latin"] });
const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

// GitHub Pages serves the site under /saylent (next.config.ts). Metadata URLs
// are plain strings, so the prefix is applied by hand, the same way
// website/app/page.tsx does it for the sample-report src.
const BASE_PATH = process.env.SITE_BASE_PATH === "1" ? "/saylent" : "";
const SITE_URL = "https://yotambraun.github.io/saylent";

const THEME_KEY = "saylent-theme";
const THEME_SCRIPT = `(function(){try{var t=localStorage.getItem('saylent-theme');var d=t==='dark'||((!t||t==='system')&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',d);}catch(e){}})();`;

// One wordmark, favicon, and social preview image used across repo, npm
// and site, plus the open-graph images (1200x630). The icon and the card
// are the same brand files the README uses, so the three surfaces cannot drift:
// website/public/brand/, generated by `npm run media`.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // The home page overrides `default` with its own full title (app/page.tsx);
  // every other route keeps the template.
  title: {
    default: "Saylent: the open-source audit of what AI assistants say about your brand",
    template: "%s · Saylent",
  },
  description:
    "The open-source audit of what AI assistants say about your brand, with the receipts: every verdict traced to the answer, the cited page, and the fix.",
  icons: {
    icon: [
      { url: `${BASE_PATH}/brand/icon.svg`, type: "image/svg+xml" },
      { url: `${BASE_PATH}/brand/icon-512.png`, type: "image/png", sizes: "512x512" },
    ],
    apple: `${BASE_PATH}/brand/icon-512.png`,
  },
  openGraph: {
    type: "website",
    siteName: "Saylent",
    url: SITE_URL,
    title: "Saylent",
    description:
      "The open-source audit of what AI assistants say about your brand, with the receipts.",
    // Resolved against metadataBase, which already carries the Pages sub-path,
    // so these must NOT be prefixed a second time (the icons above are plain
    // document links and do need the prefix).
    images: [{ url: "/brand/og-default.png", width: 1200, height: 630, alt: "Saylent" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Saylent",
    description:
      "The open-source audit of what AI assistants say about your brand, with the receipts.",
    images: ["/brand/og-wide.png"],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fraunces.variable} ${inter.variable} ${plexMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body className="min-h-full bg-background text-foreground font-sans">
        <RootProvider
          // next-themes writes the SAME localStorage key the no-FOUC script
          // above reads, so the docs sidebar toggle and the pre-paint script
          // can never disagree (before this, the toggle was a no-op because
          // no provider was mounted).
          theme={{ attribute: "class", defaultTheme: "system", enableSystem: true, storageKey: THEME_KEY }}
          // Static search: app/api/search/route.ts exports the index at build
          // time (`staticGET`), the dialog downloads it and searches in the
          // browser - the only shape that works with `output: "export"`.
          search={{ options: { type: "static", api: `${BASE_PATH}/api/search` } }}
        >
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
