// Questions and run options, per
// brand. The CLI has let an operator see the buyer questions before paying for
// them since `saylent questions` shipped; the app froze them unseen and took
// every default. This page closes that gap: the exact set, editable, with the
// samples / engines / locale / skips the CLI takes as flags, and the cost
// estimate in front of the Run button.
//
// Nothing here spends anything. The question set is generated by the same
// deterministic template pass the pipeline freezes (engine questions.ts, via the
// confirm page's buildPreviewQuestions) from the brand model already stored on
// the brand, so there is no model call to make and no "regenerate" button to
// pay for. Sharpening the questions means sharpening the brand model, which is
// what the link to brand settings is for.
import { notFound } from "next/navigation";
import type { Question } from "@saylent/engine/types";
import { ALL_ENGINES, frozenEngines } from "@saylent/engine/engines";
import { PROFILES } from "@saylent/engine/profiles";
import { TEMPLATE_SET_VERSION } from "@saylent/engine/questions";
import { type RunOptions } from "@/lib/question-options";
import { resolveRunProfile } from "@/lib/runs";
import { createClient } from "@/lib/supabase/server";
import { baselineDraft } from "./baseline";
import { QuestionsClient } from "./questions-client";

export const metadata = { title: "Questions and run options · Saylent" };

export default async function QuestionsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();

  // RLS scopes this to the owner. maybeSingle + the explicit split: a genuinely
  // missing brand is a 404, a DB error reaches the error boundary.
  const { data: brand, error } = await supabase
    .from("brands")
    .select(
      "id,name,domain,category,icp,competitors,problems,engines,question_set,question_set_version,run_options",
    )
    .eq("id", id)
    .is("deleted_at", null)
    .maybeSingle();
  if (error) throw error;
  if (!brand) notFound();

  // A brand with a run already in flight can't start another (createRun refuses,
  // and the button says so before the click rather than after).
  const { data: active } = await supabase
    .from("runs")
    .select("id")
    .eq("brand_id", id)
    .in("status", ["queued", "running"])
    .limit(1)
    .maybeSingle();

  const questionSet = brand.question_set as { questions?: Question[]; engines?: string[] } | null;
  const options = (brand.run_options as RunOptions | null) ?? null;

  // Fixed on the server so the client's first render matches: {year} lands in
  // the category questions, and a re-render must not shift it.
  const year = new Date().getFullYear();
  const baseline = baselineDraft(
    {
      name: brand.name,
      category: brand.category ?? null,
      icp: brand.icp ?? null,
      competitors: (brand.competitors as string[] | null) ?? null,
      problems: (brand.problems as string[] | null) ?? null,
      question_set: questionSet,
    },
    year,
  );

  // The profile this account's audits actually run at decides the default sample
  // count and the number of fix drafts the estimate has to pay for.
  const profile = resolveRunProfile({
    wantsSmoke: process.env.AUDIT_PROFILE === "smoke",
    isProduction: process.env.VERCEL_ENV === "production",
  });

  return (
    <QuestionsClient
      brandId={brand.id}
      brandName={brand.name}
      domain={brand.domain}
      profile={profile}
      defaultSamples={PROFILES[profile].scoredSamples}
      baseline={baseline}
      savedQuestions={options?.questions ?? null}
      savedSamples={options?.samples ?? null}
      savedEngines={options?.engines ?? null}
      savedLocale={options?.locale ?? ""}
      savedSkip={options?.skip ?? {}}
      brandEngines={frozenEngines(questionSet, (brand.engines as string[] | null) ?? null)}
      allEngines={[...ALL_ENGINES]}
      hasFrozenSet={!!questionSet?.questions?.length}
      questionSetVersion={(brand.question_set_version as number | null) ?? 1}
      templateSetVersion={TEMPLATE_SET_VERSION}
      activeRunId={active?.id ?? null}
    />
  );
}
